### ISSUE TITLE
notes

### ISSUE THREAD

**Issue by prabodhpanindre** [waqidvolli/nyu-fire-research#13]
Notes  feature: The text in notes box disappear going from one slide to next. It should not.

Can you also customize the email that user receives: 

![image](https://cloud.githubusercontent.com/assets/22395315/21078766/b5a6e2d0-bf48-11e6-9a5a-fe3077ad73b3.png)

Email Title should be "ALIVE Notes"
From should be: fire.research@nyu.edu

I dont like that "example.com"

**Comment by waqidvolli** [comment]
From has been set as fire.research@nyu.edu
Subject has been set as ALIVE Notes

<img width="267" alt="screen shot 2016-12-12 at 7 36 58 pm" src="https://cloud.githubusercontent.com/assets/17418961/21122810/7bc48968-c0a2-11e6-84fc-4501518bd081.png">

**Comment by waqidvolli** [comment]
Notes have been made persistent between slide navigation in a session. 
For this, notes widget initialization is done just one time by using an _isNotesInitialized_ flag.
