### ISSUE TITLE
email

### ISSUE THREAD

**Issue by prabodhpanindre** [waqidvolli/nyu-fire-research#14]
When user clicks on email feature, the email should go to prabodhpanindre@gmail.com
Email title should be "Query from Session ID: ####" 
From should be: the email that he used for logging in.

**Comment by waqidvolli** [comment]
Admin email has been updated to prabodhpanindre@gmail.com
Subject has been updated to  "Query from Session ID: ####"
From has been updated to the user email

<img width="563" alt="screen shot 2016-12-12 at 7 36 37 pm" src="https://cloud.githubusercontent.com/assets/17418961/21122862/c844b65a-c0a2-11e6-9172-2108ecc46995.png">
