### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by prabodhpanindre** [waqidvolli/nyu-fire-research#5]
FAQ: Last question in FAQ  - can u add new line and indentation for bullets.

sometimes this error comes and the program behaves weird.

**Comment by waqidvolli** [comment]
<img width="914" alt="screen shot 2016-10-15 at 4 18 51 am" src="https://cloud.githubusercontent.com/assets/17418961/19408571/aa600ac8-928e-11e6-939d-741e1c96bcd5.png">
