### ISSUE TITLE
% of Completion

### ISSUE THREAD

**Issue by prabodhpanindre** [waqidvolli/nyu-fire-research#8]
For L Users
Pre-test + Pre-survey =25%
All Recursive Scenarios = 50%  (that means after correct answer for each scenario = 50% / number of Scenario)
Post-Test + post-survey = 25%

For R Users

All Recursive Scenarios = 100%  (that means after correct answer for each scenario = 100% / number of Scenario)

**Comment by prabodhpanindre** [comment]
May be we can show progress bar using the scale above

**Comment by waqidvolli** [comment]
Added progress bar. Also saving and restoring the state.
