### ISSUE TITLE
fitbit 

### ISSUE THREAD

**Issue by prabodhpanindre** [waqidvolli/nyu-fire-research#9]
fitbit tracking for multiple users

**Comment by waqidvolli** [comment]
Generated separate access tokens for the 2 devices. We then make requests for each user data using their corresponding tokens. 

The same logic would apply for additional devices. We would have to generate access tokens for each new device (one time task).

**Comment by waqidvolli** [comment]
Access to the Intraday Time Series is only available for personal use (accessing your own data). You cannot access other user data. We would need special access permissions from Fitbit team if we need to do that.

Read more here: https://dev.fitbit.com/docs/heart-rate/#get-heart-rate-intraday-time-series

**Comment by waqidvolli** [comment]
Requested for access from Fitbit team.
